### SOLICITUDES EXITOSAS
###importante actualizar el ID de las peticiones exitosas!

POST http://localhost:8088/app/user
Accept: application/json
Content-Type: application/json

{
  "name": "Carolina",
  "mail": "carolina@hotmail.com",
  "password": "caro123",
  "RoleId":1
}

### voy a subir 2 recetas asi después cuando haga un get x id de user se muestran

POST http://localhost:8088/app/recetas
Content-Type:application/json
Accept: application/json

{
  "nombre": "Milanga",
  "tipo": "argentina",
  "llevaCarne" : "true",
  "UserId": 1
}

<> 2024-11-21T195344.200.json
###
POST http://localhost:8088/app/recetas
Content-Type:application/json
Accept: application/json

{
  "nombre": "Locro",
  "tipo": "argentina",
  "llevaCarne" : "true",
  "UserId": 1
}

GET http://localhost:8088/app/user/1

<> 2024-11-21T195454.200.json
<> 2024-11-21T195359.200.json

POST http://localhost:8088/app/user
Accept: application/json
Content-Type: application/json

{
  "name": "Lara",
  "mail": "lara@hotmail.com",
  "password": "lara123",
  "RoleId":2
}

<> 2024-11-21T195425.200.json

###
GET http://localhost:8088/app/recetas

<> 2024-11-21T195603.200.json
<> 2024-11-21T195540.200.json

### muestro q funciona el put en user
PUT http://localhost:8088/app/user/2
Content-Type:application/json
Accept: application/json

{
  "name": "Laruwu",
  "mail": "lara@hotmail.com",
  "password": "lara123",
  "RoleId":2

}

<> 2024-11-21T195439.200.json

### muestro q funciona el put en receta

PUT http://localhost:8088/app/recetas/1
Content-Type:application/json
Accept:application/json

{
  "nombre": "Milanesa de carne",
  "tipo": "argentina",
  "llevaCarne": true,
  "UserId": 1
}

<> 2024-11-21T195515.200.json

### elimino una receta y un user para demostrar k funcionan
DELETE http://localhost:8088/app/user/2

<> 2024-11-21T195533.200.json
###
DELETE http://localhost:8088/app/recetas/2

<> 2024-11-21T195552.200.json


### AHORA DE SOLICITUDES NO EXITOSAS PARA QUE SE MUESTRE COMO SE HANDLEAN LOS ERRORES Y QUE NO SE CRASHEA EL SERVER.

POST http://localhost:8088/app/user
Accept: application/json
Content-Type: application/json

{
  "name": " ",
  "mail": " ",
  "password": " ",
  "RoleId":1
}

<> 2024-11-21T195624.400.json


###

POST http://localhost:8088/app/recetas
Accept: application/json
Content-Type: application/json

{
  "nombre": " ",
  "tipo": " ",
  "llevaCarne" : " ",
  "UserId": 1
}

<> 2024-11-21T195659.400.json

### previamente hice un delete from users en MySQL y delete from receta
GET http://localhost:8088/app/user
Accept:application/json

<> 2024-11-21T195740.404.json
###
GET http://localhost:8088/app/recetas
Accept:application/json

<> 2024-11-21T195750.404.json
### get x id inexistente
GET http://localhost:8088/app/recetas/99
Accept:application/json
###
GET http://localhost:8088/app/user/99
Accept:application/json
### post con violaciones a las validaciones
POST http://localhost:8088/app/user
Accept: application/json
Content-Type: application/json

{
  "name": " ",
  "mail": " ",
  "password": " ",
  "RoleId":1
}
###
POST http://localhost:8088/app/recetas
Accept: application/json
Content-Type: application/json

{
  "nombre": " ",
  "tipo": " ",
  "llevaCarne" : " ",
  "UserId": 1
}
### delete a elementos inexistentes 
DELETE http://localhost:8088/app/user/99
Accept:application/json
###
DELETE http://localhost:8088/app/recetas/99
Accept:application/json
### put a elementos inexistentes
###
PUT http://localhost:8088/app/user/99
Accept: application/json
Content-Type: application/json

{
  "name": "Raul",
  "mail": "raul@hotmail.com",
  "password": "raul133",
  "RoleId":1
}

###
PUT http://localhost:8088/app/recetas/99
Accept: application/json
Content-Type: application/json

{
  "nombre": "Milanga",
  "tipo": "argentina",
  "llevaCarne" : "true",
  "UserId": 1
}
